Repository otterbrix/otterbrix, pull requests merged in 2023-08, with the labels that each got.

#224 New msgpack serializer adaptation
  components/document/document.hpp
  components/document/serializer.cpp
  components/document/serializer.hpp
  components/document/serializer/msgpack_reader.hpp
  components/document/serializer/msgpack_writer.hpp
  components/document/serializer/output_adapters.hpp
  components/document/serializer/sax.hpp
  components/document/serializer/utils.hpp
  components/document/test/test_document_json.cpp
  components/document/test/test_serializer.cpp
  components/tests/generaty.cpp
  components/tests/generaty.hpp
  components/wasm_runner/CMakeLists.txt
  components/wasm_runner/tests/CMakeLists.txt
  services/CMakeLists.txt
  services/wasm/CMakeLists.txt
  services/wasm/tests/CMakeLists.txt
  wasm/log_quickjs_wasm/CMakeLists.txt
  wasm/log_wasm/CMakeLists.txt
Labels: bug

#246 SQL-parser: ORDER BY
  components/sql/CMakeLists.txt
  components/sql/parser/base/parse_error.hpp
  components/sql/parser/base/parser_mask.cpp
  components/sql/parser/base/parser_mask.hpp
  components/sql/parser/base/parser_orderby.cpp
  components/sql/parser/base/parser_orderby.hpp
  components/sql/parser/select/impl/parser_select_base.cpp
  components/sql/test/test_parser_select.cpp
  integration/cpp/test/test_collection_sql.cpp
  services/collection/CMakeLists.txt
  services/collection/planner/create_plan.cpp
  services/collection/planner/impl/create_plan_sort.cpp
  services/collection/planner/impl/create_plan_sort.hpp
Labels: enhancement

#248 SQL-parser: fields in select
  components/sql/CMakeLists.txt
  components/sql/lexer/token.cpp
  components/sql/parser/select/impl/parser_select_fields.cpp
  components/sql/parser/select/impl/parser_select_fields.hpp
  components/sql/parser/select/impl/parser_select_from.cpp
  components/sql/parser/select/impl/parser_select_from.hpp
  components/sql/parser/select/impl/parser_select_without_from.cpp
  components/sql/parser/select/impl/parser_select_without_from.hpp
  components/sql/parser/select/parser_select.cpp
  components/sql/test/test_parser_select.cpp
Labels: enhancement

#249 SQL-parser: GROUP BY
  components/sql/CMakeLists.txt
  components/sql/lexer/token.cpp
  components/sql/lexer/token.hpp
  components/sql/parser/base/parse_error.hpp
  components/sql/parser/base/parser_groupby.cpp
  components/sql/parser/base/parser_groupby.hpp
  components/sql/parser/base/parser_orderby.cpp
  components/sql/parser/select/impl/parser_select_fields.cpp
  components/sql/parser/select/impl/parser_select_fields.hpp
  components/sql/parser/select/impl/parser_select_from.cpp
  components/sql/parser/select/impl/parser_select_without_from.cpp
  components/sql/test/test_parser_select.cpp
  integration/cpp/test/test_collection_sql.cpp
  services/collection/CMakeLists.txt
  services/collection/planner/create_plan.cpp
  services/collection/planner/impl/create_plan_group.cpp
  services/collection/planner/impl/create_plan_group.hpp
Labels: enhancement

#251 memory_storage
  components/ql/base.hpp
  components/ql/ql_statement.hpp
  components/ql/statements.hpp
  components/ql/statements/create_collection.hpp
  components/ql/statements/create_database.hpp
  components/ql/statements/drop_collection.hpp
  components/ql/statements/drop_database.hpp
  components/session/session.cpp
  components/session/session.hpp
  core/handler_by_id.hpp
  integration/cpp/CMakeLists.txt
  integration/cpp/base_spaces.cpp
  integration/cpp/base_spaces.hpp
  integration/cpp/route.hpp
  integration/cpp/test/CMakeLists.txt
  integration/cpp/test/test_collection.cpp
  integration/cpp/wrapper_dispatcher.cpp
  integration/cpp/wrapper_dispatcher.hpp
  integration/python/CMakeLists.txt
  integration/python/spaces.hpp
  integration/python/wrapper_collection.cpp
  services/CMakeLists.txt
  services/collection/collection.cpp
  services/collection/collection.hpp
  services/collection/create_index.cpp
  services/collection/tests/CMakeLists.txt
  services/collection/tests/operators/test_operator_generaty.hpp
  services/dispatcher/dispatcher.cpp
  services/dispatcher/dispatcher.hpp
  services/dispatcher/session.cpp
  services/memory_storage/CMakeLists.txt
  services/memory_storage/memory_storage.cpp
  services/memory_storage/memory_storage.hpp
  services/memory_storage/result.cpp
  services/memory_storage/result.hpp
  services/memory_storage/route.hpp
Labels: enhancement

#252 Remove manager databases
  services/database/CMakeLists.txt
  services/database/database.cpp
  services/database/database.hpp
  services/database/forward.hpp
  services/database/result_database.hpp
  services/database/route.hpp
  services/database/tests/CMakeLists.txt
  services/database/tests/main.cpp
Labels: refactoring
